### ISSUE TITLE
Include juggler's test suite

### ISSUE THREAD

**Issue by bajtos** [dittach/loopback-connector-riak#2]
loopback-datasource-juggler comes with few test suites that should be run by all connectors to ensure they correctly implement the expected connector API.

At the moment, there are two files that should be included in a connector test suite: `test/persistence-hooks.suite.js` ([example](https://github.com/strongloop/loopback-connector-mysql/blob/master/test/persistence-hooks.test.js)) and `test/common.batch.test` ([example]( https://github.com/strongloop/loopback-connector-mysql/blob/master/test/imported.test.js)).

The latter expects `global.getDataSource` and `global.should` objects to be defined.

**Comment by onyxrev** [comment]
Thanks! I'll check it out and see how it does.

**Comment by onyxrev** [comment]
I'm working on this but Riak's use of Solr for searching means that there is an indeterminate delay between the insertion of an object and the queryability of it. The test suite does not account for this delay.

**Comment by onyxrev** [comment]
It's not possible to test this connector completely with the juggler test suite.

**Comment by bajtos** [comment]
> It's not possible to test this connector completely with the juggler test suite.

That's sad. Is there anything particular that's preventing you from using the juggler test suite? Is there any way how to modify the test suite to make it work for Riak too? I am personally open to modify juggler's test suite to accommodate for as many connectors as possible.
