### ISSUE TITLE
Cannot find riak connector

### ISSUE THREAD

**Issue by duffn** [dittach/loopback-connector-riak#5]
I must be missing something obvious here as I've used a half dozen other connectors previously.

Create application
`slc loopback`

Install connector
`npm install --save loopback-connector-riak`

Add to datasources.json
```
  "rdb": {
    "name":         "rdb",
    "debug":        false,
    "host":         "127.0.0.1",
    "port":         8098,
    "bucketPrefix": "Test",
    "connector":    "riak"
  }
```

Start the app
`node server/server.js`

Get this
```
WARNING: LoopBack connector "riak" is not installed as any of the following modules:

 ./connectors/riak
loopback-connector-riak
riak

To fix, run:

    npm install riak


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error:
WARNING: LoopBack connector "riak" is not installed as any of the following modules:

 ./connectors/riak
loopback-connector-riak
riak

To fix, run:

    npm install riak
```

**Comment by onyxrev** [comment]
@duffn looks like we're missing async as a dependency in package.json.  For now add 
```
"async": "~0.9.0"
```
to your package.json and it'll probably work.

**Comment by onyxrev** [comment]
@duffn I pushed 0.0.9 with the async dependency listed

**Comment by duffn** [comment]
@onyxrev Adding
`"async": "~0.9.0"`
did it.

Thanks for the prompt response. Your connector is next up here: https://strongloop.com/strongblog/node-js-loopback-js-couchbase-connector/ :+1:
