### ISSUE TITLE
connect to bucket type !?

### ISSUE THREAD

**Issue by behrad** [dittach/loopback-connector-riak#7]
I've created a bucket time via
`riak-admin bucket-type create {"props": {"type": "message" }}`
but `http://192.168.100.194:8098/buckets?buckets=true` doesn't show my bucket!

loopback-connector-riak also faces a `TypeError: Cannot read property 'indexOf' of undefined` at
`if (buckets.indexOf(bucketName) === -1) return callback(null, false);`

however riak-admin list shows my bucket activated!
Is there any thing I should do for configuring my bucket?

**Comment by onyxrev** [comment]
@behrad Please give version 0.1.1 a try. I think this was an issue with Node v0.12, which we weren't on just yet.  I removed the bucket check.

**Comment by onyxrev** [comment]
Dup of #4

**Comment by behrad** [comment]
will test and post if any problem still exists.
Thank you @onyxrev

**Comment by behrad** [comment]
an step forward @onyxrev but I'm getting an error after I created my model: https://github.com/dittach/loopback-connector-riak/issues/3

Should I prepare riak before?
